---
deployment:
  tasks:
    - export DEPLOYPATH=/home/me87nikn96tv/public_html/
    - /bin/cp -R templates $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
