# Generated by Django 5.2.8 on 2026-03-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('pet_type', models.CharField(blank=True, max_length=120)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'adoption_seekers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RehomeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('pet_type', models.CharField(blank=True, max_length=120)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rehome_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelTable(
            name='subscriber',
            table='newsletter',
        ),
    ]
